version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django-app
    command: python /todo/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./todo:/todo
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=mydatabase
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=password
      - DJANGO_SECRET_KEY=supersecretkey

  db:
    image: mysql:8
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=mydatabase
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=password
volumes:
  db_data: