# Generated by Django 5.0.6 on 2024-06-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=64)),
                ('task_due', models.IntegerField()),
                ('is_finished', models.BooleanField()),
            ],
        ),
    ]
