# Generated by Django 5.0.6 on 2024-07-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_tasks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_due',
            field=models.DateTimeField(verbose_name='Due Date'),
        ),
    ]
