# Generated by Django 5.0.6 on 2024-07-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_tasks_task_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
