# Generated by Django 5.0.6 on 2024-07-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
